export const ACTIONS =  {
    SET_PARTICIPANTS : "SET_PARTICIPANTS",
    SET_PARTICIPANTS_NAME : "SET_PARTICIPANTS_NAME",
    FETCH_ACTIVITIES : "FETCH_ACTIVITIES",
    SET_ACTIVITIES: "SET_ACTIVITIES"
}
